- name: Deshabilitar display manager activo (si existe)
  shell: |
    DM=$(systemctl list-units --type=service | grep -i "display manager" | awk '{print $1}' || true)
    if [ -n "$DM" ]; then
      systemctl disable "$DM" || true
    fi
  args:
    warn: false

- name: Instalar lightdm
  apt:
    name: [lightdm, lightdm-gtk-greeter]
    state: present
  when: "display_manager == 'lightdm'"

- name: Activar lightdm
  systemd:
    name: lightdm.service
    enabled: yes
    state: started
  when: "display_manager == 'lightdm'"

- name: Instalar sddm
  apt:
    name: [sddm, sddm-theme-maui]
    state: present
  when: "display_manager == 'sddm'"

- name: Activar sddm
  systemd:
    name: sddm.service
    enabled: yes
    state: started
  when: "display_manager == 'sddm'"

- name: Instalar ly (experimental) - intenta compilar con Zig
  block:
    - name: Instalar dependencias para ly
      apt:
        name: [build-essential, libpam0g-dev, libxcb-xkb-dev, xauth, xserver-xorg, brightnessctl, git, wget]
        state: present
    - name: Descargar Zig
      get_url:
        url: "{{ zig_url }}"
        dest: "/tmp/{{ zig_version }}.tar.xz"
        mode: '0644'
    - name: Extraer Zig
      unarchive:
        src: "/tmp/{{ zig_version }}.tar.xz"
        dest: /opt
        remote_src: yes
    - name: Clonar ly
      git:
        repo: https://codeberg.org/fairyglade/ly.git
        dest: /tmp/ly
    - name: Compilar ly
      command: "/opt/{{ zig_version }}/zig build"
      args:
        chdir: /tmp/ly
    - name: Install ly (experiment)
      command: "/opt/{{ zig_version }}/zig build installexe"
      args:
        chdir: /tmp/ly
    - name: Enable ly
      systemd:
        name: ly.service
        enabled: yes
        state: started
  when: "display_manager == 'ly'"
  ignore_errors: yes
