---
- name: Instalar paquetes comunes para Xorg WMs
  ansible.builtin.apt:
    name:
      - adwaita-icon-theme
      - alsa-utils
      - arandr
      - dmenu
      - dunst
      - fastfetch
      - feh
      - ffmpeg
      - gvfs
      - gvfs-backends
      - lxappearance
      - lxpolkit
      - mtp-tools
      - network-manager-gnome
      - pavucontrol
      - picom
      - picom-conf
      - playerctl
      - rofi
      - sxhkd
      - terminator
      - wlogout
    state: present
  when: install_wms | length > 0
