- name: Compruebo conectividad a deb.debian.org
  ansible.builtin.uri:
    url: https://deb.debian.org
    method: HEAD
    status_code: 200
  register: internet_check
  failed_when: internet_check is failed

- name: Hacer backup de sources.list
  ansible.builtin.copy:
    src: /etc/apt/sources.list
    dest: /etc/apt/sources.list.bak
    remote_src: yes
  ignore_errors: yes

- name: Añadir contrib non-free si falta
  ansible.builtin.replace:
    path: /etc/apt/sources.list
    regexp: '^(deb .* trixie .* main)\b'
    replace: '\1 contrib non-free'
  notify: update apt cache

- name: Añadir non-free-firmware line if missing
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    line: 'deb http://deb.debian.org/debian trixie non-free-firmware'
    state: present
  notify: update apt cache

- name: Instalar paquetes básicos (git, dialog, xdg-user-dirs)
  apt:
    name: [git, dialog, xdg-user-dirs, curl, unzip]
    state: present
    update_cache: yes

- name: Crear directorios de usuario necesarios
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ lookup('env','USER') }}"
  loop:
    - "{{ lookup('env','HOME') }}/.config"
    - "{{ lookup('env','HOME') }}/.local"
    - "{{ lookup('env','HOME') }}/.local/share"
    - "{{ lookup('env','HOME') }}/.local/src"

- name: Crear /usr/local/bin si no existe
  file:
    path: /usr/local/bin
    state: directory
    mode: '0755'

- name: Actualizar cache apt
  apt:
    update_cache: yes

handlers:
  - name: update apt cache
    apt:
      update_cache: yes
